---
- name: Transfer and execute a script.
  hosts: server
  user: ubuntu
  tasks:

  - name: Creates directory
    file: path=/home/ubuntu/test state=directory

  - name: Transfer the script
    copy: src=./test.sh dest=/home/ubuntu/test.sh mode=0777

  - name: Execute the script
    command: sh /home/ubuntu/test.sh
